# Generated by Django 6.0.7 on 2026-07-22 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'Subjects',
                'ordering': ['subject_name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subject', to='student.student')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='student.subject')),
            ],
            options={
                'verbose_name': 'Subject Marks',
                'verbose_name_plural': 'Subjects Marks',
                'db_table': 'student_marks',
                'unique_together': {('subject', 'student')},
            },
        ),
    ]
