# Generated by Django 6.0.7 on 2026-07-22 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_subjectmarks_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_rank', models.IntegerField(max_length=100)),
                ('date_of_report_generation', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_report_car', to='student.student')),
            ],
            options={
                'verbose_name': 'Student Rank',
                'db_table': 'student_rank',
                'ordering': ['student_rank'],
                'unique_together': {('student_rank', 'date_of_report_generation')},
            },
        ),
    ]
