# Generated by Django 6.0.7 on 2026-07-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_reportcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='student_rank',
            field=models.IntegerField(),
        ),
    ]
